---
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: kube-monkey
    namespace: kube-system
  data:
    config.toml: |
      [kubemonkey]
      dry_run = false
      run_hour = 8
      start_hour = 9
      end_hour = 20
      blacklisted_namespaces = ["kube-system"]
      time_zone = "Europe/Berlin"

      #[debug]
      #enabled= true
      #schedule_immediate_kill= true
