---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-monkey
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-monkey
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-monkey
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-monkey
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: kube-monkey
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-monkey
    spec:
      serviceAccountName: kube-monkey
      containers:
        - name: kube-monkey
          command:
            - "/kube-monkey"
          args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
          image: ayushsobti/kube-monkey:v0.3.0
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/kube-monkey"
      volumes:
        - name: config-volume
          configMap:
            name: kube-monkey
