---
apiVersion: v1
kind: Namespace
metadata:
  name: test
  labels:
    apps: web-based
  annotations:
    type: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: test
spec:
  selector:
    matchLabels:
      app: hello
  replicas: 15
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: wardviaene/http-echo
          env:
            - name: TEXT
              value: hello
            - name: NEXT
              value: "world.test.svc.cluster.local:30001"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: test
  labels:
    app: hello
spec:
  ports:
    - port: 30000
      targetPort: 8080
  selector:
    app: hello
---
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: hello
#  namespace: test
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: hello
#  minReplicas: 1
#  maxReplicas: 15
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 50
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world
  namespace: test
spec:
  selector:
    matchLabels:
      app: world
  replicas: 15
  template:
    metadata:
      labels:
        app: world
    spec:
      containers:
        - name: world
          image: wardviaene/http-echo
          env:
            - name: TEXT
              value: world
            - name: NEXT
              value: "world2.test.svc.cluster.local:30002"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: world
  namespace: test
  labels:
    app: world
spec:
  ports:
    - port: 30001
      targetPort: 8080
  selector:
    app: world
---
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: world
#  namespace: test
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: world
#  minReplicas: 1
#  maxReplicas: 15
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 50
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: world2
  namespace: test
spec:
  selector:
    matchLabels:
      app: world2
  replicas: 15
  template:
    metadata:
      labels:
        app: world2
    spec:
      containers:
        - name: world2
          image: wardviaene/http-echo
          env:
            - name: TEXT
              value: "!!!"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: world2
  namespace: test
  labels:
    app: world2
spec:
  ports:
    - port: 30002
      targetPort: 8080
  selector:
    app: world2
---
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: world2
#  namespace: test
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: world2
#  minReplicas: 1
#  maxReplicas: 15
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 50
#---
